name: 错误反馈
description: '提交 LINUX DO WIKI 漏洞'
title: '[错误] '
labels: ["【错误】"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: 为避免重复提交，在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      options:
        - label: 我已在标题简短的描述了我所遇到的问题
        - label: 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题

  - type: dropdown
    attributes:
      label: 操作系统
      description: 请提供操作系统类型
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 浏览器版本
      description: 请提供使用的浏览器版本
      multiple: true
      options:
        - Edge
        - Chorme
        - Firefox
        - 手机系统默认浏览器
  - type: input
    attributes:
      label: 系统及浏览器版本
      description: 请提供出现问题的操作系统及使用的浏览器版本
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述
      description: 请提供错误的详细描述。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现方式
      description: 请提供重现错误的步骤
    validations:
      required: true
  - type: textarea
    attributes:
      label: 社区个人主页
      description: 请提供社区个人主页
    validations:
      required: true
