name: 功能请求
description: '请求 LINUX DO WIKI 功能'
title: '[建议] '
labels: ["【建议】"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: 为避免重复提交，在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      options:
        - label: 我已在标题简短的描述了我所需的功能
        - label: 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
        - label: 我未在当前版本找到我所需的功能
  - type: textarea
    attributes:
      label: 描述
      description: 请提供所需功能的详细描述
    validations:
      required: true
  - type: textarea
    attributes:
      label: 社区个人主页
      description: 请提供社区个人主页
    validations:
      required: true
